-- =============================================================================
-- MERCADOLIBRE ITEM DETAIL API - DATABASE SCHEMA
-- =============================================================================

-- Tabla de Categorías
CREATE TABLE IF NOT EXISTS categories (
                                          id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    path_from_root TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

-- Tabla de Vendedores
CREATE TABLE IF NOT EXISTS sellers (
                                       id BIGINT PRIMARY KEY,
                                       nickname VARCHAR(100) NOT NULL,
    permalink VARCHAR(500),
    registration_date TIMESTAMP,
    country_id VARCHAR(10),
    reputation_level VARCHAR(20),
    power_seller_status VARCHAR(20),
    transactions_completed INT DEFAULT 0,
    transactions_canceled INT DEFAULT 0,
    rating_positive DECIMAL(5,4) DEFAULT 0,
    rating_negative DECIMAL(5,4) DEFAULT 0,
    rating_neutral DECIMAL(5,4) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

-- Tabla Principal de Items
CREATE TABLE IF NOT EXISTS items (
                                     id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    price_amount BIGINT NOT NULL,
    price_currency VARCHAR(10) DEFAULT 'ARS',
    price_decimals INT DEFAULT 2,
    condition_type VARCHAR(20) NOT NULL,
    available_quantity INT DEFAULT 0,
    sold_quantity INT DEFAULT 0,
    permalink VARCHAR(500),
    status VARCHAR(20) DEFAULT 'active',
    category_id VARCHAR(50),
    seller_id BIGINT,
    description TEXT,
    listing_type VARCHAR(50),
    buying_mode VARCHAR(50),
    free_shipping BOOLEAN DEFAULT false,
    local_pick_up BOOLEAN DEFAULT false,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (seller_id) REFERENCES sellers(id)
    );

-- Tabla de Atributos de Items
CREATE TABLE IF NOT EXISTS item_attributes (
                                               id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                               item_id VARCHAR(50) NOT NULL,
    attribute_id VARCHAR(100) NOT NULL,
    attribute_name VARCHAR(255) NOT NULL,
    attribute_value VARCHAR(500) NOT NULL,
    attribute_unit VARCHAR(50),
    value_type VARCHAR(20) DEFAULT 'string',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
    );

-- Tabla de Imágenes de Items
CREATE TABLE IF NOT EXISTS item_pictures (
                                             id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                             item_id VARCHAR(50) NOT NULL,
    picture_id VARCHAR(100) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    secure_url VARCHAR(1000) NOT NULL,
    size VARCHAR(20) DEFAULT '500x500',
    max_size VARCHAR(20) DEFAULT '1200x1200',
    quality VARCHAR(20) DEFAULT 'high',
    picture_order INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
    );

-- Tabla de Métodos de Envío
CREATE TABLE IF NOT EXISTS shipping_methods (
                                                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                                item_id VARCHAR(50) NOT NULL,
    method_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    cost BIGINT DEFAULT 0,
    currency VARCHAR(10) DEFAULT 'ARS',
    free_shipping BOOLEAN DEFAULT false,
    estimated_min_days INT,
    estimated_max_days INT,
    local_pick_up BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
    );

-- Tabla de Garantía
CREATE TABLE IF NOT EXISTS item_warranty (
                                             id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                             item_id VARCHAR(50) NOT NULL,
    warranty_type VARCHAR(100),
    warranty_time VARCHAR(50),
    warranty_description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
    );

-- Tabla de Métodos de Pago
CREATE TABLE IF NOT EXISTS payment_methods (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               item_id VARCHAR(50) NOT NULL,
    installments_quantity INT,
    installments_rate DECIMAL(5,2),
    installment_amount DECIMAL(15,2),
    accepts_credit_card BOOLEAN DEFAULT false,
    accepts_debit_card BOOLEAN DEFAULT false,
    accepts_mercadopago BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
    );

-- Índices para optimizar consultas
CREATE INDEX IF NOT EXISTS idx_items_category ON items(category_id);
CREATE INDEX IF NOT EXISTS idx_items_seller ON items(seller_id);
CREATE INDEX IF NOT EXISTS idx_items_status ON items(status);
CREATE INDEX IF NOT EXISTS idx_item_attributes_item_id ON item_attributes(item_id);
CREATE INDEX IF NOT EXISTS idx_item_pictures_item_id ON item_pictures(item_id);
CREATE INDEX IF NOT EXISTS idx_shipping_methods_item_id ON shipping_methods(item_id);

-- =============================================================================
-- TABLA DE PERSONAS (PERSON DOMAIN)
-- =============================================================================

CREATE TABLE IF NOT EXISTS persons (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    document_type VARCHAR(10) NOT NULL,
    document_number VARCHAR(20) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    second_name VARCHAR(50),
    first_last_name VARCHAR(50) NOT NULL,
    second_last_name VARCHAR(50),
    birth_date DATE NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone_number VARCHAR(20) NOT NULL,
    address VARCHAR(200),
    city VARCHAR(100),
    country VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_person_document UNIQUE (document_type, document_number)
);

-- Índices para la tabla persons
CREATE INDEX IF NOT EXISTS idx_persons_document ON persons(document_type, document_number);
CREATE INDEX IF NOT EXISTS idx_persons_email ON persons(email);
CREATE INDEX IF NOT EXISTS idx_persons_status ON persons(status);
CREATE INDEX IF NOT EXISTS idx_persons_name ON persons(first_name, first_last_name);